steps:
  - label: ':pipeline:'
    plugins:
      - thedyrt/skip-checkout#v0.1.1: ~
    commands: 
      - >
        echo "
        steps:
          - label: ':toolbox:'
            command: >
              echo \"
                steps:       
                  - label: ':docker: Build'
                    command: 'true'
                    plugins:
                      - thedyrt/skip-checkout#v0.1.1: ~
                  - wait
                  - group: ':hammer: Setup'
                    steps:
                      - label: ':bundler: Bundle'
                        key: bundler
                        command: 'true'
                        plugins:
                          - thedyrt/skip-checkout#v0.1.1: ~
                      - label: ':yarn: Packages'
                        key: packages
                        command: 'true'
                        plugins:
                          - thedyrt/skip-checkout#v0.1.1: ~
                  - label: Random Work
                    command: 'true'
                    plugins:
                      - thedyrt/skip-checkout#v0.1.1: ~
                  - wait
                  - group: ':hammer: Setup'
                    steps:
                      - label: 'Error annotation'
                        command: "buildkite-agent annotate --context boo --style error \"ERROR ANNOTATION\""
                        soft_fail:
                          - exit_status: "*"
                      - label: 'Cool chill step'
                        command: true
                      - label: 'Block step'
                        block: "Release"
                        prompt: "Fill out the details for release"
                        fields:
                          - text: "Release Name"
                            key: "release-name"
                  - label: ':rspec: RSpec'
                    depends_on:
                      - bundler
                    command: 'true'
                    plugins:
                      - thedyrt/skip-checkout#v0.1.1: ~
              \" | buildkite-agent pipeline upload
            plugins:
              - thedyrt/skip-checkout#v0.1.1: ~
        " | buildkite-agent pipeline upload
      - sleep 60 