steps:
  - label: "Important step that must run!"
    command: 'true'
  - wait
  - group: "addons"
    steps:
    - label: ":hammer: Example Script"
      command: 'true'
    - label: ":hammer: Example Script #2"
      command: 'true'

