steps:
  - group: "addons"
    steps:
    - label: ":hammer: Example Script"
      commands: 
      - "script.sh"
      - "buildkite-agent pipeline upload nested.yml"
      artifact_paths: "artifacts/*"
      agents:
        queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
