steps:
  - label: ':pipeline:'
    plugins:
      - thedyrt/skip-checkout#v0.1.1: ~
    commands: 
      - >
        echo "
        steps:
          - label: ':toolbox:'
            command: >
              echo \"
                steps:       
                  - label: ':docker: Build'
                    command: 'true'
                    plugins:
                      - thedyrt/skip-checkout#v0.1.1: ~
                  - wait
                  - group: ':hammer: Setup'
                    steps:
                      - label: ':bundler: Bundle'
                        key: bundler
                        command: 'true'
                        plugins:
                          - thedyrt/skip-checkout#v0.1.1: ~
                      - label: ':yarn: Packages'
                        key: packages
                        command: 'true'
                        plugins:
                          - thedyrt/skip-checkout#v0.1.1: ~

                            - group: ":pencil: Annotations 3"
                      - group: ":pencil: Nested Group"
                      key: nested group
                      steps:
                        - command: "buildkite-agent annotate --context boo --style error \"ERROR ANNOTATION\""
                          label: "Error annotation"
                        - command: "buildkite-agent annotate --context meh --style default \"DEFAULT ANNOTATION\"; false"
                          label: "Default annotation"
                          parallelism: 3
                        - command: "buildkite-agent annotate --context meh --style default \"DEFAULT ANNOTATION\""
                          label: "Default annotation"
                          parallelism: 6
                  - label: Random Work
                    command: 'true'
                    plugins:
                      - thedyrt/skip-checkout#v0.1.1: ~
                  - label: ':rspec: RSpec'
                    depends_on:
                      - bundler
                    command: 'true'
                    plugins:
                      - thedyrt/skip-checkout#v0.1.1: ~
              \" | buildkite-agent pipeline upload
            plugins:
              - thedyrt/skip-checkout#v0.1.1: ~
        " | buildkite-agent pipeline upload
      - sleep 60 